# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sum in Blog
tagline:          'A Jekyll theme'
description: |
  무언가를 깨트리는 것은<br>
  경계를 부풀리는 새로움을<br>
  전해줄 것이다

url:              "https://rouhalee.github.io"
baseurl:          /

author:
  name:           이수민
  email:          "sumofi@naver.com"
  instagram_username: "@sum.in.s"

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist

